package com.pkukielka

import geoslick.PostgisDriver.extended._
import com.vividsolutions.jts.geom.{Point,Geometry}

object PlanetOSMLine extends PostgisTable[(Int, String, Geometry)]("planet_osm_line") {

  def osm_id =              column[Int]("osm_id")
  def access =              column[String]("access")
  def housename =           column[String]("addr:housename")
  def addr_housenumber =    column[String]("addr:housenumber")
  def addr_interpolation =  column[String]("addr:interpolation")
  def admin_level =         column[String]("admin_level")
  def aerialway =           column[String]("aerialway")
  def aeroway =             column[String]("aeroway")
  def amenity =             column[String]("amenity")
  def area =                column[String]("area")
  def barrier =             column[String]("barrier")
  def bicycle =             column[String]("bicycle")
  def brand =               column[String]("brand")
  def bridge =              column[String]("bridge")
  def boundary =            column[String]("boundary")
  def building =            column[String]("building")
  def construction =        column[String]("construction")
  def covered =             column[String]("covered")
  def culvert =             column[String]("culvert")
  def cutting =             column[String]("cutting")
  def denomination =        column[String]("denomination")
  def disused =             column[String]("disused")
  def embankment =          column[String]("embankment")
  def foot =                column[String]("foot")
  def generator_source =    column[String]("generator:source")
  def harbour =             column[String]("harbour")
  def highway =             column[String]("highway")
  def historic =            column[String]("historic")
  def horse =               column[String]("horse")
  def intermittent =        column[String]("intermittent")
  def junction =            column[String]("junction")
  def landuse =             column[String]("landuse")
  def layer =               column[String]("layer")
  def leisure =             column[String]("leisure")
  def lock =                column[String]("lock")
  def man_made =            column[String]("man_made")
  def military =            column[String]("military")
  def motorcar =            column[String]("motorcar")
  def name =                column[String]("name")
  def natural =             column[String]("natural")
  def oneway =              column[String]("oneway")
  def operator =            column[String]("operator")
  def population =          column[String]("population")
  def power =               column[String]("power")
  def power_source =        column[String]("power_source")
  def place =               column[String]("place")
  def railway =             column[String]("railway")
  def ref =                 column[String]("ref")
  def religion =            column[String]("religion")
  def route =               column[String]("route")
  def service =             column[String]("service")
  def shop =                column[String]("shop")
  def sport =               column[String]("sport")
  def surface =             column[String]("surface")
  def toll =                column[String]("toll")
  def tourism =             column[String]("tourism")
  def tower_type =          column[String]("tower:type")
  def tracktype =           column[String]("tracktype")
  def tunnel =              column[String]("tunnel")
  def water =               column[String]("water")
  def waterway =            column[String]("waterway")
  def wetland =             column[String]("wetland")
  def width =               column[String]("width")
  def wood =                column[String]("wood")
  def z_order =             column[Int]("z_order")
  def way_area =            column[Double]("way_area")
  def way =                 geoColumn[Point]("way", 900913)

  def * = osm_id ~ name ~ way
}